# Generated by Django 5.0.6 on 2024-08-13 18:50

import apis.models
import cloudinary.models
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Product1", "Product1"),
                            ("Product2", "Product2"),
                            ("Product3", "Product3"),
                        ],
                        default="Product1",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField()),
                ("price", models.FloatField()),
                ("quantity", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("remaining_quantity", models.IntegerField()),
                ("unlist", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=100)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(default="", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("farmer", "Farmer"),
                            ("consumer", "Consumer"),
                            ("admin", "Admin"),
                        ],
                        default="consumer",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="image"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apis.product"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="apis.user"
            ),
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_method", models.CharField(default="CASH", max_length=10)),
                ("accepted", models.BooleanField(default=False)),
                ("quantity", models.IntegerField(default=0)),
                ("completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apis.product"
                    ),
                ),
                (
                    "consumer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumer_contracts",
                        to="apis.user",
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farmer_contracts",
                        to="apis.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VerificationDocs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "addhar_card",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="addhar"
                    ),
                ),
                (
                    "pan_card",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="pan-card"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=apis.models.get_first_user_or_unknown,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="apis.user",
                    ),
                ),
            ],
        ),
    ]
