# Generated by Django 5.0.6 on 2024-08-29 14:19

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AlterField(
            model_name="verificationdocs",
            name="addhar_card",
            field=models.FileField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(
                    "your.storage.backend.module.SupabaseStorage"
                ),
                upload_to="addhar/",
            ),
        ),
        migrations.AlterField(
            model_name="verificationdocs",
            name="pan_card",
            field=models.FileField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(
                    "your.storage.backend.module.SupabaseStorage"
                ),
                upload_to="pan-card/",
            ),
        ),
    ]
