# Generated by Django 5.0.6 on 2024-08-29 16:13

import cloudinary_storage.storage
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0002_user_last_login_alter_verificationdocs_addhar_card_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="verificationdocs",
            name="addhar_card",
            field=models.FileField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(
                    "SupabaseStorage"
                ),
                upload_to="addhar/",
            ),
        ),
        migrations.AlterField(
            model_name="verificationdocs",
            name="pan_card",
            field=models.FileField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(
                    "SupabaseStorage"
                ),
                upload_to="pan-card/",
            ),
        ),
    ]
