# Generated by Django 5.0.6 on 2024-08-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0003_alter_user_phone_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default="", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
