# Generated by Django 5.0.6 on 2024-08-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0004_remove_user_name_user_username_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
