# Generated by Django 5.0.6 on 2024-08-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0006_alter_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
