# Generated by Django 5.0.6 on 2024-08-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0008_user_groups_user_user_permissions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
