# Generated by Django 5.0.6 on 2024-08-29 16:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0009_user_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="VerificationDocs",
            new_name="FarmerVerificationDocs",
        ),
    ]
