# Generated by Django 5.0.6 on 2024-08-29 19:19

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0010_rename_verificationdocs_farmerverificationdocs"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmerverificationdocs",
            name="satbaarcopy",
            field=models.FileField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(
                    "SupabaseStorage"
                ),
                upload_to="satbaarcopy/",
            ),
        ),
    ]
