# Generated by Django 5.0.6 on 2024-08-29 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0013_alter_farmerverificationdocs_addhar_card_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmerverificationdocs",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
