# Generated by Django 5.0.6 on 2024-09-02 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0014_alter_farmerverificationdocs_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsumerVerificationDocs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "addhar_card",
                    models.FileField(blank=True, null=True, upload_to="addhar/"),
                ),
                (
                    "pan_card",
                    models.FileField(blank=True, null=True, upload_to="pan-card/"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
