# Generated by Django 5.0.6 on 2024-09-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0015_consumerverificationdocs"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
